DROP SCHEMA IF EXISTS testpython;
CREATE SCHEMA testpython;
USE testpython;
DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
	id int(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(45) DEFAULT NULL,
    last_name VARCHAR(45) DEFAULT NULL,
    email VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;